# Site settings
title: 徐国菡
email: xgh726@msn.cn
description: na
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

