# Site settings
title: 徐国菡
email: xgh726@msn.cn
#url: "http://xuguohan.github.io/myblog" 
url:      "" # does not include hostname


# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "myblog" # does not include hostname




# Build settings
markdown: kramdown

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

